- name: "Install Telegraf"
  yum:
    name: "{{telegraf_url}}"
    state: present
- name: "Upload Telegraf configuration"
  template:
    src: templates/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
- name: "Start Telegraf"
  service:
    name: "telegraf"
    state: restarted  

